JBEHAVE-1528 Fix NPE in junit execution tree
jbehave/jbehave-core pull request #21
Opened 2021-12-21 07:56 UTC by uarlouski

2021-12-23 11:32 UTC, valfirst requested changes

2021-12-23 11:32 UTC, valfirst commented on jbehave-core/src/test/java/org/jbehave/core/junit/JUnit4DescriptionGeneratorBehaviour.java
> +        lenient().when(allStepCandidates.getBeforeScenarioSteps(any())).thenReturn(List.of());
List#of - Java 9+ only

2021-12-23 20:28 UTC, valfirst approved these changes

2021-12-24 08:27 UTC, ikalinin1 approved these changes

2021-12-24 08:48 UTC, uarlouski commented
In master https://github.com/jbehave/jbehave-core/commit/09991347b39f5ba4db80b97434672adef79fbfca

2021-12-24 08:48 UTC, closed without merging