JBEHAVE-1550 Fix examples tables for filtered by meta given stories
jbehave/jbehave-core pull request #30
Opened 2022-07-13 13:31 UTC by Tatsiana-Luchonak

Cherry-picked from https://github.com/valfirst/jbehave-core/commit/7a6e9a9c3371997c6325844d64be93f7c2dbbb89

2022-07-13 15:16 UTC, valfirst requested changes

2022-07-13 15:16 UTC, valfirst commented on jbehave-core/src/main/java/org/jbehave/core/model/GivenStories.java
> +            if (story.hasAnchorExamples() ){
```suggestion
            if (story.hasAnchorExamples()){
```

2022-07-13 15:16 UTC, valfirst commented on jbehave-core/src/main/java/org/jbehave/core/model/GivenStory.java
> +    public boolean hasAnchorExamples() {
```suggestion
    public boolean hasAnchorWithExamplesReference() {
```

2022-07-13 15:16 UTC, valfirst commented on jbehave-core/src/test/java/org/jbehave/core/parsers/RegexStoryParserBehaviour.java
> +        assertThat(givenStory.hasAnchorExamples(), equalTo(false));
I think it makes sense to add the positive test as well (or update any existing one if present)

2022-07-14 09:28 UTC, uarlouski approved these changes

2022-07-14 10:04 UTC, valfirst approved these changes

2022-07-14 10:08 UTC, valfirst commented
Pulled with thanks!

2022-07-14 10:08 UTC, closed without merging