JBEHAVE-1553 Adapt JUnit tree generator for conditional steps
jbehave/jbehave-core pull request #37
Opened 2022-08-11 12:53 UTC by uarlouski

2022-08-11 15:07 UTC, valfirst requested changes

2022-08-11 15:07 UTC, valfirst commented on jbehave-core/src/main/java/org/jbehave/core/junit/JUnit4DescriptionGenerator.java
> +        } else if (matchingStep.getStepsType() == null) {
```suggestion
        } else if (matchingStep instanceof ConditionalStepCandidate) {
```

2022-08-11 16:11 UTC, valfirst approved these changes

2022-08-11 17:51 UTC, ikalinin1 approved these changes

2022-08-15 11:34 UTC, uarlouski commented
In master https://github.com/jbehave/jbehave-core/commit/b702674746e0ac039f6c7a6f4ed55f856d9dcdb0

2022-08-15 11:34 UTC, closed without merging